name: check code quality

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

env:
  GO_VERSION: "1.20"

jobs:
  lint:
    name: run golangci-lint
    runs-on: arc-runner-set
    container: buildpack-deps:jammy
    steps:
      - name: Install capsh
        run: |
          apt-get update
          apt-get install -y libcap2-bin
      - name: System Information
        run: |
          who
          id
          capsh --print
          mount
          ls -la
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.53.3

  vet:
    name: run go vet
    container: buildpack-deps:jammy
    runs-on: arc-runner-set
    steps:
      - name: Install capsh
        run: |
          apt-get update
          apt-get install -y libcap2-bin
      - name: System Information
        run: |
          who
          id
          capsh --print
          mount
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - run: make vet

  acc_test:
    name: run acc test
    runs-on: arc-runner-set
    container: buildpack-deps:jammy
    steps:
      - name: Install capsh
        run: |
          apt-get update
          apt-get install -y libcap2-bin
      - name: System Information
        run: |
          who
          id
          capsh --print
          mount
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - run: |
          echo "Starting synthetic acceptance test..."
          sleep 15
          echo "Synthetic acceptance test completed successfully."

  eco_check:
    name: eco/check
    if: always()
    needs: [lint, vet, acc_test]
    runs-on: arc-runner-set
    container: buildpack-deps:jammy
    steps:
      - name: Install Python and capsh
        run: |
          apt-get update
          apt-get install -y python3 python3-pip libcap2-bin
          ln -s /usr/bin/python3 /usr/bin/python
      - name: System Information
        run: |
          who
          id
          capsh --print
          mount
      - name: Link Python3 to Python
        run: |
          cat /etc/hostname
          ls -ahl /usr/bin/python*
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
