name: check code quality

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    name: run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.53.3
  vet:
    name: run go vet
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make vet

  acc_test:
    name: run acc test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'gate')
    steps:
      - name: Run synthetic acceptance test
        run: |
          echo "Starting synthetic acceptance test..."
          sleep 15
          echo "Synthetic acceptance test completed successfully."
