name: check code quality

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

env:
  GO_VERSION: "1.20"

jobs:
  lint:
    name: run golangci-lint
    runs-on: arc-runner-set
    container: buildpack-deps:jammy
    steps:
      - name: System Information
        run: |
          who
          id
          uname -a
          if ! command -v sudo &>/dev/null; then
            echo "sudo command not found."
          else
            echo "sudo is available."
          fi
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.53.3

  vet:
    name: run go vet
    container: buildpack-deps:jammy
    runs-on: arc-runner-set
    steps:
      - name: System Information
        run: |
          who
          id
          uname -a
          if ! command -v sudo &>/dev/null; then
            echo "sudo command not found."
          else
            echo "sudo is available."
          fi
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - run: make vet

  acc_test:
    name: run acc test
    runs-on: arc-runner-set
    container: buildpack-deps:jammy
    steps:
      - name: System Information
        run: |
          who
          id
          uname -a
          if ! command -v sudo &>/dev/null; then
            echo "sudo command not found."
          else
            echo "sudo is available."
          fi
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - run: |
          echo "Starting synthetic acceptance test..."
          sleep 15
          echo "Synthetic acceptance test completed successfully."

  eco_check:
    name: eco/check
    if: always()
    needs: [lint, vet, acc_test]
    runs-on: arc-runner-set
    container: ubuntu:22.04
    steps:
      - name: System Information
        run: |
          who
          id
          uname -a
          if ! command -v sudo &>/dev/null; then
            echo "sudo command not found."
          else
            echo "sudo is available."
          fi
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
